### ISSUE TITLE
用于回调消息的示例代码web.py运行出错

### ISSUE THREAD

**Issue by ppp1234** [GentleCP/corpwechat-bot#10]
源代码取自：https://gist.github.com/GentleCP
源代码未做任何修改，但是Crypto.Cipher模块pycrypto已经无法安装了，百度后使用的替代品pycryptodome（安装方式 pip install pycryptodome）
 部署到腾讯云上后可以正常运行，但是每次收发消息都会报错：

ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 373, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/python3/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/fastapi/applications.py", line 208, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/routing.py", line 580, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/routing.py", line 241, in handle
    await self.app(scope, receive, send)
  File "/usr/local/python3/lib/python3.8/site-packages/starlette/routing.py", line 52, in app
    response = await func(request)
  File "/usr/local/python3/lib/python3.8/site-packages/fastapi/routing.py", line 226, in app
    raw_response = await run_endpoint_function(
  File "/usr/local/python3/lib/python3.8/site-packages/fastapi/routing.py", line 159, in run_endpoint_function
    return await dependant.call(**values)
  File "/home/zk/mycode/wx_web/web.py", line 112, in recv
    ret, send_msg = wxcpt.EncryptMsg(sReplyMsg=sRespData, sNonce=nonce)
UnboundLocalError: local variable 'sRespData' referenced before assignment

**Comment by GentleCP** [comment]
我这边`pycrypto`还是可以装的啊，我使用的版本是2.6.1，直接用`pip`命令即可
![image](https://user-images.githubusercontent.com/38175267/132125836-e0369260-da7e-47bd-96c9-fa52b97844d6.png)
如果无法安装，尝试换个环境，参照官网的步骤：https://www.dlitz.net/software/pycrypto/

**Comment by GentleCP** [comment]
收发消息错误的原因可能有很多，首先检查你在企业微信的回调配置是否通过了，如果通过了在该应用中应该显示如下已启用API的提示：
![image](https://user-images.githubusercontent.com/38175267/132126059-8c0901e0-923d-4352-8eca-5161547b84d1.png)
然后查看相应的参数信息
![image](https://user-images.githubusercontent.com/38175267/132126072-4af22f29-dad0-4ede-a210-5c1213bfb0ec.png)

如果上面一切正常，在运行`web.py`的时候记得传入正确的参数，一个是token，一个是AESKEY, 一个是企业id，详细参考说明文档：https://corpwechatbot.gentlecp.com/%E4%BD%BF%E7%94%A8%E6%95%99%E7%A8%8B/callback_configuration/ ， 请具体确认这些步骤是否都已通过
