### ISSUE TITLE
电脑上开了clash代理，然后就会报错

### ISSUE THREAD

**Issue by yzxdd123** [GentleCP/corpwechat-bot#21]
我的clash可以正常访问外网和墙内，但不知道为啥就是corpwechatbot报错，以下是报错信息，
Traceback (most recent call last):
  File "urllib3\connectionpool.py", line 696, in urlopen
  File "urllib3\connectionpool.py", line 964, in _prepare_proxy
  File "urllib3\connection.py", line 359, in connect
  File "urllib3\connection.py", line 496, in _connect_tls_proxy
  File "urllib3\util\ssl_.py", line 432, in ssl_wrap_socket
  File "urllib3\util\ssl_.py", line 474, in _ssl_wrap_socket_impl
  File "ssl.py", line 500, in wrap_socket
  File "ssl.py", line 1040, in _create
  File "ssl.py", line 1309, in do_handshake
OSError: [Errno 0] Error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "requests\adapters.py", line 439, in send
  File "urllib3\connectionpool.py", line 755, in urlopen
  File "urllib3\util\retry.py", line 573, in increment
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='qyapi.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/gettoken?corpid=****&corpsecret=*** (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "任务计划w.py", line 16, in <module>
  File "corpwechatbot\app.py", line 57, in __init__
  File "corpwechatbot\app.py", line 62, in __fresh_msg_send_api
  File "corpwechatbot\app.py", line 107, in get_assess_token
  File "corpwechatbot\app.py", line 111, in __get_access_token
  File "requests\api.py", line 76, in get
  File "requests\api.py", line 61, in request
  File "requests\sessions.py", line 542, in request
  File "requests\sessions.py", line 655, in send
  File "requests\adapters.py", line 510, in send
requests.exceptions.ProxyError: HTTPSConnectionPool(host='qyapi.weixin.qq.com', port=443): Max retries exceeded with url: /cgi-bin/gettoken?corpid=***&corpsecret=*** (Caused by ProxyError('Cannot connect to proxy.', OSError(0, 'Error')))

**Comment by GentleCP** [comment]
参考: https://github.com/openmaptiles/openmaptiles/issues/1023
